### ISSUE TITLE
App crashed because ScannerScanCallback class definition is not found

### ISSUE THREAD

**Issue by dvermeirImec** [inthepocket/ibeacon-scanner-android#19]
Seems like there's a missing import.

```
Fatal Exception: java.lang.NoClassDefFoundError: mobi.inthepocket.android.beacons.ibeaconscanner.ScannerScanCallbackat mobi.inthepocket.android.beacons.ibeaconscanner.DefaultScanService.<init>(DefaultScanService.java:50)at mobi.inthepocket.android.beacons.ibeaconscanner.DefaultScanService.<init>(DefaultScanService.java:33)at mobi.inthepocket.android.beacons.ibeaconscanner.DefaultScanService$Initializer.build(DefaultScanService.java:314)at be.imec.apt.wappr.services.BeaconService.onCreate(BeaconService.java:62)at android.app.ActivityThread.handleCreateService(ActivityThread.java:2721)at android.app.ActivityThread.access$1900(ActivityThread.java:148)at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loop(Looper.java:137)at android.app.ActivityThread.main(ActivityThread.java:5457)at java.lang.reflect.Method.invokeNative(Method.java)at java.lang.reflect.Method.invoke(Method.java:525)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by dvermeirImec** [comment]
I'm guessing (since the import is correct) there's a difference between the what's available at compile time and at runtime.

**Comment by eliaslecomte** [comment]
Hey, Sorry I have not responded yet. I am baffled by your issue. What kind of obfuscation do you use?
